### PR TITLE
[CURATOR-548] Bump zookeeper version to 3.5.6

### PR DESCRIPTION
**Pull request by porunov**
Bumps zookeeper dependency to 3.5.6

### CODE REVIEW

**Comment by porunov** [comment]
@randgalt Will you be able to review this PR?

**Comment by Randgalt** [comment]
One of the committers will get to it eventually. But, TBH, it shouldn't block you. You can use whatever version of ZooKeeper you want.

**Comment by Randgalt** [comment]
FYI - we're likely to move to ZooKeeper 3.6.0 in the next Curator release (with a 3.5.6 test module). So, this PR may become superfluous.

**Comment by porunov** [comment]
@Randgalthat is OK. Just close this PR when it becomes obsolate

**Comment by Randgalt** [comment]
I made it `3.5.7`

**Pull request closed without merging**
