### PR TITLE
CURATOR-235 LeaderSelector.internalRequeue should be private

### PR DESCRIPTION
**Pull request by oza**

### CODE REVIEW

**Comment by bonifaido** [comment]
There is already a pull request for this: #87.

**Comment by oza** [comment]
@bonifaido OIC. I'll close this issue, so could you send a PR with the header CURATOR-235? I think #87 should be closed once.

**Comment by bonifaido** [comment]
I have closed and reopened #87 and now it is linked to the JIRA.

**Comment by oza** [comment]
:+1:

**Pull request closed without merging**
