### PR TITLE
CURATOR-481 Remove jackson-mapper-asl-version and update jackson

### PR DESCRIPTION
**Pull request by Max-Pudov**

### CODE REVIEW

**Comment by matobet** [comment]
Hi, thanks @Max-Pudov for contributing this! The security scans can get pretty annoying continuously reporting Curator for the usage of `jackson-mapper-asl`. Is there anything preventing this from getting merged?

**Comment by cammckenzie** [comment]
It looks OK to me, but my knowledge of this section of Curator is very limited. @Randgalt do you have any thoughts on this? If not, I'll merge.

**Comment by Randgalt** [comment]
Are there any implications for backward compatibility?

**Comment by cammckenzie** [comment]
@Max-Pudov @matobet 
Guys, any thoughts about backward compatibility issues?

**Comment by Randgalt** [comment]
@leventov is this PR still needed or does #301 cover the same change?

**Comment by leventov** [comment]
@Randgalt it's still needed. I could have included the changes by @Max-Pudov in my PR but didn't do it so that this PR could be merged and his authorship retained.

**Comment by mikhailvaliev** [comment]
so you guys are merging this or what?

**Comment by cammckenzie** [comment]
I'm not sure. I am not familiar with this area of the code base, and while the change seems fairly benign, my concern is that the changes will cause backwards compatibility issues. Is there any documentation you can point me to that would indicate whether this is the case or not?

**Comment by Moonergfp** [comment]
which version is release about this update ?

**Pull request merged**
