### PR TITLE
delete useless do-while loop

### PR DESCRIPTION
**Pull request by tswstarplanet**

### CODE REVIEW

**Comment by bobningx** [comment]
Yeah, this is a minor improvement. The while condition is always false.
In other files, there are still some minor improvements like this.

**Comment by tswstarplanet** [comment]
I don't know why the ci-check failed

**Comment by Randgalt** [comment]
How does this improve this code? This is merely a difference of opinion in style. I'm -1 on this. Also, all PRs should have an accompanying issue in our Jira. https://cwiki.apache.org/confluence/display/CURATOR/Submitting+Pull+Requests

**Comment by tisonkun** [comment]
Closed as inactive and meaningless.

**Pull request closed without merging**
