### PR TITLE
CURATOR-278: In transactions compressed option does not work with som…

### PR DESCRIPTION
**Pull request by granthenke**
…e fluent api combinations

### CODE REVIEW

**Comment by cammckenzie** [comment]
Looks good to me.

**Comment by Randgalt** [comment]
Has this been checked against 3.0.0 as well?

**Comment by granthenke** [comment]
@Randgalt This looks like an issue in the old transaction api in 3.0.0 too. I have not checked the new transaction api introduced via [CURATOR-215](https://issues.apache.org/jira/browse/CURATOR-215) PR #77.

**Comment by Randgalt** [comment]
We should fix it in 3.0.0 as well. A separate PR maybe?

**Comment by granthenke** [comment]
Happy to send a PR against 3.0.0. It can likely be cherry picked directly to that branch too. Whatever you guys need to get this in.

**Comment by cammckenzie** [comment]
@madrob Do you have any comments about this? If not, I'll merge and look at what's involved with getting it into 3.0 as well.

**Comment by granthenke** [comment]
@Randgalt @madrob @cammckenzie Is there something you guys need from me?

**Comment by cammckenzie** [comment]
Thanks @granthenke, I haven't heard anything from @madrob so I'll look at merging it now.

**Comment by granthenke** [comment]
@cammckenzie Thanks for the update!

**Pull request merged**
