### PR TITLE
CURATOR-603 Use Awaitility to instead of Thread sleep method in recipes module.

### PR DESCRIPTION
**Pull request by mattisonchao**
Use Awaitility to instead of Thread sleep method in recipes module.

### CODE REVIEW

**Comment by tisonkun** [comment]
I suggest you start a discussion on dev@curator.apache.org first. This is not a trivial improvement but which suite we'd prefer.

I'll close this pull request before we reach a consensus.

**Comment by mattisonchao** [comment]
Sure, and thanks for your reply.

**Comment by tisonkun** [comment]
@mattisonchao I just notice we already use awaitility in curator-client https://github.com/apache/curator/pull/389.

Then I'm OK to continue the patch.

**Comment by tisonkun** [comment]
@mattisonchao if you'd like to continue it, please merge master and ping me for review.

**Pull request closed without merging**
