### PR TITLE
CURATOR-596 Upgrade ZooKeeper to 3.7.0

### PR DESCRIPTION
**Pull request by eolivelli**

### CODE REVIEW

**Comment by cammckenzie** [comment]
Changes look fine to me, but it appears the build unit tests are failing on the CI build?

**Comment by eolivelli** [comment]
Yes.
Probably it is better to just update to latest 3.6.3 and move to 3.7.0 when I am done on #379

**Comment by eolivelli** [comment]
On the other hand people may try to use Curator with 3.7.0 and we must be sure that they do not have problems.
I will investigate the failures

**Comment by Hronom** [comment]
What the status?

**Comment by eolivelli** [comment]
@Hronom 
thanks for the reminder !

I have resolved the conflicts, if CI passes I will commit the patch.

Maybe we can follow up with a release of Curator

**Comment by tommy04062019** [comment]
Anything new here?I've waiting for this a long time

**Comment by tisonkun** [comment]
@eolivelli it seems there is still some test failure :(

**Comment by eolivelli** [comment]
we should move to 3.7.1

**Comment by tisonkun** [comment]
Resolved by #426.

**Pull request closed without merging**
