### PR TITLE
CURATOR-606: ModeledFrameworkImpl.update(T model, int version): Use version in all cases.

### PR DESCRIPTION
**Pull request by pavlov112**
Aside from the description, which captures the major issue:
- The ```fixAclList()``` change is unrelated, but jumped out as a build warning in my environment.
- There were no existing tests that exercised this class, so I didn't have any obvious place to hang a new unit test. Am I missing something obvious?

### CODE REVIEW

**Comment by cammckenzie** [comment]
Having some issues putting comments against the file.

The main fix looks good to me. As for tests, it looks like this class has none currently, any additions would be welcome though.

I'm not sure why you need to make fixAclList static though? It can certainly be static, but it's only used by this class, so it does't need to be.

**Comment by pavlov112** [comment]
Like I said, it was a build warning - Principle of Least Access applied to the "this" pointer. I've backed it out as unrelated.

**Comment by eolivelli** [comment]
Can we add some test that cover this code?

The change overall lgtm

**Comment by pavlov112** [comment]
Sorry about that. I naively expected unit tests to directly access ```ModeledFrameworkImpl```, and when I didn't find any, assumed that I was off the hook. I've added negative and positive calls to ```TestModeledFramework.testVersioned()```.

**Comment by cammckenzie** [comment]
LGTM

**Review by cammckenzie — APPROVED** [review]

**Comment by pavlov112** [comment]
Thanks for the reviews and approval. Do I need to do anything else before this can be merged?

**Review by eolivelli — APPROVED** [review]
Lgtm

I will merge when I am back from vacation, likely next week

Thank you!

**Comment by pavlov112** [comment]
Hi. It's been over a month. Do you have any plans to merge this in the near future?

**Comment by eolivelli** [comment]
I am so sorry.
Let me kickstart Travis again

**Comment by pavlov112** [comment]
Friendly nudge - all checks passed, so please merge.

**Comment by eolivelli** [comment]
Thank you very much!

**Pull request merged**
