### PR TITLE
[CURATOR-397] Strongly typed Model DSL

### PR DESCRIPTION
**Pull request by Randgalt**
This is a large PR but provides long needed modeling to ZooKeeper/Curator. I've made the PR's website doc available here: http://curator.apache.org/private/staging/curator-x-async/modeled.html

Also an example that uses all the APIs is here: https://github.com/apache/curator/tree/CURATOR-397/curator-examples/src/main/java/pubsub

The most important classes are here:

- [ZPath](https://github.com/apache/curator/blob/CURATOR-397/curator-x-async/src/main/java/org/apache/curator/x/async/modeled/ZPath.java)
- [ModelSpec](https://github.com/apache/curator/blob/CURATOR-397/curator-x-async/src/main/java/org/apache/curator/x/async/modeled/ModelSpec.java)
- [ModeledFramework](https://github.com/apache/curator/blob/CURATOR-397/curator-x-async/src/main/java/org/apache/curator/x/async/modeled/ModeledFramework.java)

Then:

- [CachedModeledFramework](https://github.com/apache/curator/blob/CURATOR-397/curator-x-async/src/main/java/org/apache/curator/x/async/modeled/cached/CachedModeledFramework.java)
- [TypedZPath](https://github.com/apache/curator/blob/CURATOR-397/curator-x-async/src/main/java/org/apache/curator/x/async/modeled/typed/TypedZPath.java)
- [TypedModelSpec](https://github.com/apache/curator/blob/CURATOR-397/curator-x-async/src/main/java/org/apache/curator/x/async/modeled/typed/TypedModelSpec.java)
- [TypedModeledFramework](https://github.com/apache/curator/blob/CURATOR-397/curator-x-async/src/main/java/org/apache/curator/x/async/modeled/typed/TypedModeledFramework.java)

### CODE REVIEW

**Comment by Randgalt** [comment]
This new feature allows code like this:

```java
// let "client" be a CuratorFramework instance

ZPath path = ZPath.parse(...);    // whatever path you need
JacksonModelSerializer<Person> serializer = JacksonModelSerializer.build(Person.class);
ModeledAsyncCuratorFramework<MyModel> modeled = ModeledAsyncCuratorFramework.wrap(client, path, serializer);

...

public void writePerson(String id, Person p) {
    modeled.at(id).create(p);   // note this is an async operation
}

public void readPerson(String id, Consumer<Person> receiver) {
    modeled.at(id).read().whenComplete((person, exception) -> {
        if ( exception != null ) {
            ...
        } else {
            receiver.accept(person);
        }
    });
}
```

**Comment by Randgalt** [comment]
Note: I've also added wrappers so that `NodeCache`, `PathChildrenCache` and `TreeCache` can have modeled usages.

**Comment by jhalterman** [comment]
This looks pretty sweet! My only comment is that this interface name is so long, ex: `ModeledAsyncCuratorFramework<MyModel>`.

**Comment by igor-kupczynski** [comment]
Awesome stuff @Randgalt I'd love to see it integrated

**Comment by Randgalt** [comment]
merged

**Pull request closed without merging**
