### PR TITLE
[CURATOR-395] Potential null dereference in PersistentNode

### PR DESCRIPTION
**Pull request by Randgalt**
localCreateMethod could be null in a race condition

### CODE REVIEW

**Comment by cammckenzie** [comment]
I think that the fix is fine, but why is the createMethod a lazily instantiated reference? Couldn't it just be a normal reference that gets created in the constructor? We seem to have everything we need there to create it.

**Comment by Randgalt** [comment]
> why is the createMethod a lazily instantiated reference? Couldn't it just be a normal reference that gets created in the constructor

It's due to https://issues.apache.org/jira/browse/CURATOR-364

**Comment by cammckenzie** [comment]
Ah, I see now. It's the Preconditions.checkState call that causes the issue. I thought that we could just hold a reference to the builder and then call forPath() on it when required. But that checkState call will fail if the client is not started.

So, the PR looks OK to me. Merge away.

**Comment by Randgalt** [comment]
TBH - I'd totally forgotten why it was done this way. I had to do a git bisect to find the reason.

**Pull request merged**
