### PR TITLE
CURATOR-281: Usage of TestingServer fails when upgrading to 3.0

### PR DESCRIPTION
**Pull request by granthenke**
Replace testng assertion with java assertion

### CODE REVIEW

**Comment by madrob** [comment]
Doesn't that effectively remove the assertion, though? Java assertions are not enabled by default, you need to specify the `-ea` flag for that.

**Comment by granthenke** [comment]
Good point, I could instead throw an IllegalStateException if the result is not true

**Comment by granthenke** [comment]
@madrob Does this follow up patch look better?

**Comment by madrob** [comment]
Yea, it looks good, I'll get that in shortly.

**Comment by granthenke** [comment]
Closing as this was committed, but not auto-closed since it was in the 3.0 branch and not the current default branch.

**Pull request closed without merging**
