### PR TITLE
CURATOR-624: Fix Github Actions by adding 'distribution' for JDK setup step

### PR DESCRIPTION
**Pull request by martin-g**
Merge the two workflows into one and use strategy.matrix for the Java
versions.

### CODE REVIEW

**Comment by eolivelli** [comment]
@nicoloboschi do you mind taking a look here ?

**Review by nicoloboschi — APPROVED** [review]
I agree we have to use 'temurin'

Good work, I will close mine

**Comment by martin-g** [comment]
It seems with one additional minor change (upgrade Mockito-core to 4.3.1) and few import fixes the build will pass with JDK 17 too.
Do you want me to do it in this PR ?

**Comment by martin-g** [comment]
I guess the test failures are expected.
At least the CI setup now works!

**Comment by eolivelli** [comment]
> It seems with one additional minor change (upgrade Mockito-core to 4.3.1) and few import fixes the build will pass with JDK 17 too.
> Do you want me to do it in this PR ?

this would be great, thanks

**Comment by eolivelli** [comment]
Maybe if you remove the jdk17 part and we see ci passing we can merge this pr and unblock the pipeline 

Does it sound  like a good plan to you?

**Comment by martin-g** [comment]
We need #409 to be merged to see green build for JDK 1.8 and 11.
I'll comment out 17!

**Comment by eolivelli** [comment]
Let's remove jdk17 stuff and merge this pr

**Comment by eolivelli** [comment]
Then we can commit your fix to the test and add back 17

**Comment by martin-g** [comment]
OK. The last commit is reverted!
I will create a new PR for it!

**Pull request merged**
