### PR TITLE
CURATOR-596: Upgrade ZooKeeper to 3.7.1

### PR DESCRIPTION
**Pull request by kezhuw**
`TestReadOnly` fails due to ZOOKEEPER-3863(apache/zookeeper#1380).

ZOOKEEPER-3863 uses `QuorumPeerConfig.localSessionsEnabled` to toggle
local sessions supports in `ReadOnlyZooKeeperServer`.

This pr populates `QuorumPeerConfig.localSessionsEnabled` and
`QuorumPeerConfig.localSessionsUpgradingEnabled` from system property
`readonlymode.enabled` for simplicity.

### CODE REVIEW

**Review by tisonkun — COMMENTED** [review]
Generally looks good. Perhaps we should add a curator-test-zk36 module for running tests with zookeeper 3.6.x to prevent regression? You may take a look at how `curator-test-zk35` does now. I'm happy to review this patch :)

cc @kezhuw

**Review by eolivelli — APPROVED** [review]
LGTM

**Comment by kezhuw** [comment]
@tisonkun I have rebased this pr to master for 5.4.0-SNAPSHOT and push a fixup commit for module `curator-test-zk36`. Could you please take a look and trigger ci workflow ?

**Review by tisonkun — APPROVED** [review]

**Comment by tisonkun** [comment]
@kezhuw Thanks for your contribution!

Merging if CI gives green.

**Comment by tisonkun** [comment]
Merging...

@kezhuw thank you very much!

**Pull request merged**
