### PR TITLE
CURATOR-519: Update zookeeper to 3.5.5 stable version

### PR DESCRIPTION
**Pull request by aseychell**
Zookeeper is now at a stable version 3.5.5 so there is no longer the need to depend on beta version

### CODE REVIEW

**Comment by Z-torres** [comment]
why this update is failed? netty 3.x was used to zookeeper from 3.4.x to 3.5.4-beta, the version of 3.5.5 is a huge imporvement by netty 4.x

**Comment by cammckenzie** [comment]
I would presume it hasn't been merged as there's no material impact to Curator, as Curator only uses the Zookeeper client, which I don't believe has changed between 3.5.4-beta and 3.5.5. We should probably update at some point though. Thoughts @Randgalt @shayshim ?

**Comment by TisonKun** [comment]
Travis fails on

```
[INFO] --- clirr-maven-plugin:2.8:check (default) @ curator-client ---
[INFO] artifact org.apache.curator:curator-client: checking for updates from sonatype
[INFO] artifact org.apache.curator:curator-client: checking for updates from sonatype-snapshots
[WARNING] repository metadata for: 'artifact org.apache.curator:curator-client' could not be retrieved from repository: sonatype-snapshots due to an error: Failed to transfer file: https://oss.sonatype.org/content/repositories/snapshots/org/apache/curator/curator-client/maven-metadata.xml. Return code is: 502 , ReasonPhrase:Bad Gateway.
[INFO] artifact org.apache.curator:curator-client: checking for updates from sonatype-apache
[INFO] artifact org.apache.curator:curator-client: checking for updates from apache-snapshots
[INFO] artifact org.apache.curator:curator-client: checking for updates from sonatype
[INFO] artifact org.apache.curator:curator-client: checking for updates from sonatype-snapshots
[WARNING] repository metadata for: 'artifact org.apache.curator:curator-client' could not be retrieved from repository: sonatype-snapshots due to an error: Failed to transfer file: https://oss.sonatype.org/content/repositories/snapshots/org/apache/curator/curator-client/maven-metadata.xml. Return code is: 502 , ReasonPhrase:Bad Gateway.
[INFO] artifact org.apache.curator:curator-client: checking for updates from sonatype-apache
[INFO] artifact org.apache.curator:curator-client: checking for updates from apache-snapshots
[INFO] Comparing to version: 4.2.0
[ERROR] 8001: org.apache.curator.shaded.com.google.common.annotations.Beta: Class org.apache.curator.shaded.com.google.common.annotations.Beta removed
[ERROR] 8001: org.apache.curator.shaded.com.google.common.annotations.GwtCompatible: Class org.apache.curator.shaded.com.google.common.annotations.GwtCompatible removed
[ERROR] 8001: org.apache.curator.shaded.com.google.common.annotations.GwtIncompatible: Class org.apache.curator.shaded.com.google.common.annotations.GwtIncompatible removed
[ERROR] 8001: org.apache.curator.shaded.com.google.common.annotations.VisibleForTesting: Class org.apache.curator.shaded.com.google.common.annotations.VisibleForTesting removed
[ERROR] 8001: org.apache.curator.shaded.com.google.common.base.Ascii: Class org.apache.curator.shaded.com.google.common.base.Ascii removed
```

maybe a temporarily issue?

**Comment by shayshim** [comment]
@cammckenzie @TisonKun I rebuilt it 3 times, and in all 3 it got stuck in TestLockACLs. I didn't look into it yet, though.

**Comment by cammckenzie** [comment]
I just pulled this branch and ran mvn test and it mostly worked. It failed one test in ZK3.4 testing, but I don't think that's an issue necessarily. The TestLockACLs certainly seemed to work ok.

**Comment by TisonKun** [comment]
@shayshim maybe it worth an issue of unstable test, could you file one and attach the log for further debugging?

**Comment by eolivelli** [comment]
Is the problem only on travis?
If so it can be due to the fact that on travis you have very limited resources.
Try to run the test by assigning only 1 core

**Comment by aseychell** [comment]
This is also failing locally.  Tried resynching with master but still failing on `org.apache.curator.framework.recipes.locks.TestLockACLs`

**Comment by aseychell** [comment]
From a thread dump on this hanging test, I have the following stack trace 
`"main" #1 prio=5 os_prio=0 cpu=327234.38ms elapsed=7654.60s tid=0x00000152c44d9800 nid=0xead8 in Object.wait()  [0x0000000316dfe000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11/Native Method)
        - waiting on <no object reference available>
        at java.lang.Thread.join(java.base@11/Thread.java:1305)
        - waiting to re-lock in wait() <0x0000000711446058> (a org.apache.zookeeper.ClientCnxn$SendThread)
        at java.lang.Thread.join(java.base@11/Thread.java:1379)
        at org.apache.zookeeper.ClientCnxn.disconnect(ClientCnxn.java:1455)
        at org.apache.zookeeper.ClientCnxn.close(ClientCnxn.java:1485)
        at org.apache.zookeeper.ZooKeeper.close(ZooKeeper.java:1415)
        - locked <0x00000007115ffa98> (a org.apache.zookeeper.ZooKeeper)
        at org.apache.curator.HandleHolder.internalClose(HandleHolder.java:160)
        at org.apache.curator.HandleHolder.closeAndClear(HandleHolder.java:78)
        at org.apache.curator.ConnectionState.close(ConnectionState.java:125)
        at org.apache.curator.CuratorZookeeperClient.close(CuratorZookeeperClient.java:266)
        at org.apache.curator.CuratorZookeeperClient.close(CuratorZookeeperClient.java:249)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.close(CuratorFrameworkImpl.java:411)
        at org.apache.curator.shaded.com.google.common.io.Closeables.close(Closeables.java:78)
        at org.apache.curator.utils.CloseableUtils.closeQuietly(CloseableUtils.java:59)
        at org.apache.curator.framework.recipes.locks.TestLockACLs.testACLsCreatingParents(TestLockACLs.java:94)
        at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11/DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(java.base@11/Method.java:566)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
        at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
        at org.testng.TestRunner.privateRun(TestRunner.java:648)
        at org.testng.TestRunner.run(TestRunner.java:505)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
        at org.testng.SuiteRunner.run(SuiteRunner.java:364)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
        at org.testng.TestNG.runSuites(TestNG.java:1049)
        at org.testng.TestNG.run(TestNG.java:1017)
        at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
        at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)`

**Comment by Randgalt** [comment]
All PRs should have an associated issue in our Jira: https://cwiki.apache.org/confluence/display/CURATOR/Submitting+Pull+Requests

**Comment by eolivelli** [comment]
FYI zk 3.5.6 we be cut soon.
Maybe it is worth to wait for it

**Comment by aseychell** [comment]
Sorry I was not aware of the need to open a JIRA ticket.  However, found an issue already in JIRA related to this: https://issues.apache.org/jira/browse/CURATOR-519

**Pull request merged**
