### PR TITLE
CURATOR-516: Remove Deprecated newSetFromMap

### PR DESCRIPTION
**Pull request by belugabehr**

### CODE REVIEW

**Comment by BELUGABEHR** [comment]
Hello @Randgalt.

You were able to help me with a previous Curator PR.  Can I get your help once more?  Thanks.

**Comment by Randgalt** [comment]
What's the benefit of this?

**Comment by tisonkun** [comment]
@Randgalt Guava's `Sets.newSetFromMap` is a wrapper of `Collections.newSetFromMap` and there is a deprecation comments: `Use {@link Collections#newSetFromMap} instead.`

However, this change is not quite necessary as we can always handle it when a version bump of Guava cause this method removed or we'd like to (it's less possible, although) remove dependency of Guava.

**Comment by tisonkun** [comment]
Closed as Not A Problem.

**Pull request closed without merging**
