### PR TITLE
[CURATOR-99] Java 8 DSL for Curator

### PR DESCRIPTION
**Pull request by Randgalt**
Curator Async is a brand new DSL that wraps existing CuratorFramework instances. This new DSL is entirely asynchronous and uses Java 8's CompletionStage mechanism for chaining, composing, etc. Additionally, Curator's original DSL has been cleaned up and simplified, in particular for operations such as create().

### CODE REVIEW

**Comment by Randgalt** [comment]
Reviewers, please review the doc too: https://github.com/Randgalt/curator-1/blob/88fee0eac4a48e9391edf8997a5a20e14c1c18a7/curator-x-async/src/site/confluence/index.confluence

**Comment by Randgalt** [comment]
FYI - here's an image of the Curator Async webpage: 
curator async

**Comment by Randgalt** [comment]
FYI - here's an image of the Curator Async webpage:
[Curator Async.pdf](https://github.com/apache/curator/files/721561/Curator.Async.pdf)

**Comment by cammckenzie** [comment]
I don't have any real experience with the Java 8 asynch framework, but what you've implemented looks good to me. I'll have a look at the doco next week when I get some time (on leave at the moment).

**Comment by Randgalt** [comment]
Thanks Cam!

**Comment by Randgalt** [comment]
Barring objections I'm going to merge this. Speak now...

**Pull request merged**
