### PR TITLE
CURATOR-576 Import merge script from ZooKeeper project

### PR DESCRIPTION
**Pull request by eolivelli**

### CODE REVIEW

**Comment by Randgalt** [comment]
What does this do?

**Comment by eolivelli** [comment]
Sorry @Randgalt for the confusion
I have sent an email to dev@curator.apache.org

This is the JIRA with full instructions (I have merged now the instructions that I sent on the ML)
https://issues.apache.org/jira/browse/CURATOR-576

The docs are here
https://cwiki.apache.org/confluence/display/ZOOKEEPER/Merging+Github+Pull+Requests

we will have our own page once the script is merged

**Comment by Randgalt** [comment]
I'm -1 on this. This can be run locally by someone interested in it. The scripts can live on our wiki. Personally, I wouldn't use them.

**Comment by eolivelli** [comment]
@Randgalt 
Having a script helps the community in doing things all the same way and saves us from making errors.

We can make it non required.

**Comment by andrepappa** [comment]
> What does this do?

what do you mean?

**Comment by xianjeng21** [comment]
hmmmmm

**Comment by anmolnar** [comment]
@Randgalt This script is super useful for ZooKeeper commits. It makes the process super fast and easy for everyone. Is it really better to keep scripts on a wiki instead of source control? People should use their own handmade rubbish instead of an official and well maintained script?
Sorry for horning in, this patch just caught my eye.

**Comment by Randgalt** [comment]
OK, sure

**Comment by eolivelli** [comment]
@anmolnar @Randgalt 
I am taking your discussion as finally "let's merge this script"

**Pull request merged**
