### PR TITLE
CURATOR-586: Check if namespace is not null

### PR DESCRIPTION
**Pull request by nryanov**
https://issues.apache.org/jira/browse/CURATOR-586

### CODE REVIEW

**Review by eolivelli — CHANGES_REQUESTED** [review]
thanks for your fix.
can you please add a minimal test case in order to prevent regressions in the future ?

**Comment by nryanov** [comment]
Done 👍

**Comment by Randgalt** [comment]
I recall that every time we've touched this in the past there were problems. I'd feel more comfortable if some users tested this with their code.

**Comment by TisonKun** [comment]
> I recall that every time we've touched this in the past there were problems. I'd feel more comfortable if some users tested this with their code.

Is there an exact example? What is the problems' kind?

**Comment by tisonkun** [comment]
@nryanov as @cammckenzie mentioned in the JIRA ticket, Curator handles nullity correctly internally. You may provide a real-world use case to make this change. Otherwise, it can be closed as unnecessary.

**Comment by tisonkun** [comment]
Closed as inactive.

**Pull request closed without merging**
