### PR TITLE
CURATOR-602 fix typo in TestGroupMember.java

### PR DESCRIPTION
**Pull request by colinkuo**

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
Lgtm

Good catch

**Comment by eolivelli** [comment]
I will merge on Monday (I do not have my laptop now sorry)

**Comment by colinkuo** [comment]
Thanks for the quick response.

**Comment by tisonkun** [comment]
@colinkuo Thanks for your contribution. I'm curious why previous the test doesn't fail due to this typo.

**Comment by colinkuo** [comment]
@tisonkun The existing assertion statements in this test case are not smart enough to catch this typo. I'd say this was a *coincidence.

**Comment by eolivelli** [comment]
committed to master branch!
thank you

**Pull request merged**
