### PR TITLE
[CURATOR-160] Add builders and dsl for ZooKeeper's config and reconfig m...

### PR DESCRIPTION
**Pull request by iocanel**
...ethods.

### CODE REVIEW

**Comment by kondratovich** [comment]
Hi, any update on this?

**Comment by iocanel** [comment]
Yeah,

I think that I’ll have it in by the end of the week.

**Comment by kondratovich** [comment]
```java
    // org/apache/curator/framework/imps/GetConfigBuilderImpl.java#52
    @Override
    public Ensembleable<byte[]> storingStatIn(Stat stat) {
        this.stat = new Stat();
        return this;
    }
````

Seems you are ignoring specified `Stat` object.

**Comment by Randgalt** [comment]
There's a new master tracking branch ref'd by #76

**Pull request closed without merging**
