### PR TITLE
CURATOR-523: Fix ByteBuffer's compatibility issues

### PR DESCRIPTION
**Pull request by asdf2014**

### CODE REVIEW

**Comment by asdf2014** [comment]
@leventov @Randgalt @pacomendes PTAL

**Comment by pacomendes** [comment]
Thanks, LGTM

**Comment by leventov** [comment]
LGTM, although I don't see how the diff relates to the title of the PR.

**Comment by asdf2014** [comment]
@pacomendes @leventov  Thank you for your comments. This title is mainly used to indicate that the underlying purpose of this PR is to resolve ByteBuffer compatibility issues caused by the JDK version. :sweat_smile:

**Comment by asdf2014** [comment]
@shayshim Can we move this forward? Apache Druid wants to upgrade to the new version of Curator, but it was blocked by this issue. More details: https://github.com/apache/incubator-druid/pull/8177

**Comment by pacomendes** [comment]
@Randgalt can we merge this in?

**Comment by Randgalt** [comment]
I'll try to get to it soon. Or maybe @shayshim or @cammckenzie can do it.

**Comment by shayshim** [comment]
@Randgalt @asdf2014 I can get to it soon too

**Pull request merged**
