### PR TITLE
CURATOR-624 Fix GitHub actions

### PR DESCRIPTION
**Pull request by nicoloboschi**
We need to specify the JDK distribution. I set the 'adopt' one

### CODE REVIEW

**Comment by nicoloboschi** [comment]
closing to retrigger actions

**Comment by martin-g** [comment]
I've just created https://github.com/apache/curator/pull/407 and now I noticed this PR.
IMO mine is a bit better because of two reasons:
* AdoptJDK has been donated to Eclipse Foundation and now its name is `Temurin`
* I've merged the two workflows into one and used `strategy.matrix` to test with the different versions. This way it would be easier to test with more JDK versions, e.g. `17`

**Comment by eolivelli** [comment]
thank you @nicoloboschi and @martin-g 

I think @martin-g 's patch is better

**Comment by eolivelli** [comment]
@nicoloboschi I am sorry this patch became stale

**Comment by nicoloboschi** [comment]
no problem, we can merge the other one

**Pull request closed without merging**
