### PR TITLE
Add getNodeName() to Lease

### PR DESCRIPTION
**Pull request by Randgalt**

### CODE REVIEW

**Comment by cammckenzie** [comment]
Looks ok to me.

**Comment by oza** [comment]
@Randgalt the patch itself looks good to me too, but it's stale. Could you rebase it? If you are busy, I would like to success your work.

**Comment by Randgalt** [comment]
If you can submit a new PR it would be appreciated

**Comment by oza** [comment]
@Randgalt Sure. Created #191

**Pull request closed without merging**
