### PR TITLE
make it public  

### PR DESCRIPTION
**Pull request by windcaller31**
make it public 
and remove final 
i can use my  executorService

### CODE REVIEW

**Comment by windcaller31** [comment]
sorry , I make mistake  ,  just make the function public  , 
and I've  add  the "final"

**Comment by cammckenzie** [comment]
Could you please raise a JIRA defect for this explaining what this PR fixes?

**Comment by windcaller31** [comment]
> Could you please raise a JIRA defect for this explaining what this PR fixes?

ok，Give me a few days

**Comment by tisonkun** [comment]
Closed as invalid. This patch may be useful. But please first create a JIRA ticket and then we can revive this thread.

**Pull request closed without merging**
