### PR TITLE
CURATOR-625 Bump directory maven plugin version to 1.0

### PR DESCRIPTION
**Pull request by nicoloboschi**
When running `mvn clean install -DskipTests` on my Mac i get:

`Failed to execute goal org.commonjava.maven.plugins:directory-maven-plugin:0.1:highest-basedir (directories) on project apache-curator: Cannot find a single highest directory for this project set. First two candidates directories don't share a common root. -> [Help 1]`

Upgrading the plugin, I'm able to compile

### CODE REVIEW

**Comment by martin-g** [comment]
I face the same error on Ubuntu 20.04.
The error does not say what exactly is the problem. It is a fresh checkout of https://github.com/apache/curator 
I wondered how the CI works but it appears the CI is broken since a while - https://github.com/apache/curator/actions
Applying the fix from this PR helped me!

**Comment by nicoloboschi** [comment]
CI is in bad shape. @eolivelli  would you mind to merge this anyway ?

**Comment by martin-g** [comment]
It is interesting that this plugin failed only on Linux ARM64. It works fine with 0.1 on Linux x86_64.

**Comment by martin-g** [comment]
@nicoloboschi  Please rebase to latest master!

**Comment by eolivelli** [comment]
committed to master branch
thank you @nicoloboschi

**Pull request merged**
