### PR TITLE
CURATOR-588 Upgrade ZooKeeper to 3.6.2

### PR DESCRIPTION
**Pull request by eolivelli**

### CODE REVIEW

**Comment by cammckenzie** [comment]
Looks fine to me, I can't see any changes in ZK 3.6.2 that will cause any issues with Curator.

**Comment by liran2000** [comment]
@eolivelli / @cammckenzie 
can this be resolved and merged please ?

ZooKeeper to 3.6.1 or higher is needed for a new method exposed, for fixing an issue.

**Comment by eolivelli** [comment]
I have not merged this patch because I am working on the upgrade to 3.6.3 before cutting the release.

see #386

**Comment by eolivelli** [comment]
this patch is superseded by #386

**Comment by martin-g** [comment]
This PR could be closed

**Pull request closed without merging**
