### PR TITLE
CURATOR-225: Added new ErrorMode value KEEP.

### PR DESCRIPTION
**Pull request by zzcoder**
Added ErrorMode.KEEP. Created a new test-case testKeepMode() to make sure it works.

If the new mode is not used, the code should work as is so the impact of this change is very limited.

### CODE REVIEW

**Comment by madrob** [comment]
Hi zzcoder! Thank you for your contribution and especially for including a test. I'm a little confused about how this behaviour is supposed to differ from `REQUEUE`. Can you please clarify the intent for me? Thanks!

**Comment by zzcoder** [comment]
@madrob With REQUEUE, the entry is removed from the queue and appended to the back of the queue,  it violates the FIFO principal of the queue and it matters to our application. With the added option, the item will be kept in the queue intact.

**Comment by Randgalt** [comment]
Maybe we should have REQUEUE attempt to put it back where it was instead of adding a new mode.

**Comment by zzcoder** [comment]
@Randgalt I thought about that and it's problematic. The queue uses SEQUENTIAL flag. The sequence number determines the order in the queue. It seems that you have to tamper with ZooKeeper to achieve that.

**Comment by Randgalt** [comment]
For the requeue, the sequence number has already been used so a simple create with the same sequence number would work.

**Comment by Randgalt** [comment]
@zzcoder any updates on this?

**Comment by zzcoder** [comment]
This PULL request is not needed anymore.

**Pull request closed without merging**
