### PR TITLE
[CURATOR-653] Proposed changes based on PR #398

### PR DESCRIPTION
**Pull request by XComp**
This closes #398.

This PR is based on PR #398 and adds a few comments from [my review of that PR](https://github.com/apache/curator/pull/398#pullrequestreview-1134363474)

This PR addresses the review comments individually in separate commits to make it easier to select the ones that are relevant. The final commit is a proposal where I refactor using plain Strings in the eventQueue but rather proper objects that enables us to monitor the latch that triggered the event.

### CODE REVIEW

**Comment by XComp** [comment]
```
2022-10-10T13:50:53.7756841Z [INFO] Running org.apache.curator.framework.recipes.cache.TestPathChildrenCache
2022-10-10T15:00:44.1920989Z ##[error]The operation was canceled.
```
hm, looks like CI ran into a timeout exceeding the maximum threshold for a CI run of 120min due to `TestPathChildrenCache` :thinking:

**Comment by XComp** [comment]
The timeout of {{TestPathChildrenCache}} in the [Java 11 CI job](https://github.com/apache/curator/actions/runs/3219514422/jobs/5264980959#step:6:1595) seems to be unrelated to this PR's change: It doesn't utilize `LeaderLatch` as far as I can see. I created CURATOR-657 to cover this test instability

**Review by tisonkun — APPROVED** [review]
LGTM.

@eolivelli you may take a looks at this patch which I think is identical to #398.

We may not always wait for new patches so it's on you when to cut the release. I'll regard this patch and #435 are both not blockers.

**Comment by tisonkun** [comment]
Merging...

**Pull request merged**
